Addition of the --root allows to work around this issue:
mkdir: impossible de créer le répertoire « /nix/store/4hjzqv35mv6brygb8ys0zic7bgiyj6v1-mininet-2.2.2 »: Permission denied
install flags: install SHELL=/nix/store/xn5gv3lpfy91yvfy9b0i7klfcxh9xskz-bash-4.4-p19/bin/bash mnexec PYTHON=/nix/store/c7h3k65wr2r8z1295h1s4dh4phv13zpn-python-2.7.14-env/bin/python2.7 PREFIX=\$\(out\) VERSION=\'\"2.2.2\"\' install PREFIX=\$\(out\) PYTHONDIR=\"\$\(py\)\" PYTHON=/nix/store/c7h3k65wr2r8z1295h1s4dh4phv13zpn-python-2.7.14-env/bin/python2.7
mkdir -p /home/teto/scratch/mininet/toto/share/man/man1
install mn.1 mnexec.1 /home/teto/scratch/mininet/toto/share/man/man1
install -D mnexec /home/teto/scratch/mininet/toto/bin/mnexec
/nix/store/c7h3k65wr2r8z1295h1s4dh4phv13zpn-python-2.7.14-env/bin/python2.7 setup.py install --prefix=""/home/teto/scratch/mininet/py""
/nix/store/c7h3k65wr2r8z1295h1s4dh4phv13zpn-python-2.7.14-env/lib/python2.7/site-packages/setuptools-39.0.1-py2.7.egg/setuptools/dist.py:406: UserWarning: The version specified ('2.3.0d1') is an invalid version, this may not work as expected with newer versions of setuptools, pip, and PyPI. Please see PEP 440 for more details.
running install
Checking .pth file support in /home/teto/scratch/mininet/py/lib/python2.7/site-packages/
/nix/store/l9j2jsc9flrbmpf799nw9wdq59gpwms8-python-2.7.14/bin/python2.7 -E -c pass
TEST FAILED: /home/teto/scratch/mininet/py/lib/python2.7/site-packages/ does NOT support .pth files
error: bad install directory or PYTHONPATH

You are attempting to install a package to a directory that is not
on PYTHONPATH and which Python does not read ".pth" files from.  The
installation directory you specified (via --install-dir, --prefix, or
the distutils default setting) was:

    /home/teto/scratch/mininet/py/lib/python2.7/site-packages/

and your PYTHONPATH environment variable currently contains:

    ''

Here are some of your options for correcting the problem:

* You can choose a different installation directory, i.e., one that is
  on PYTHONPATH or supports .pth files

* You can add the installation directory to the PYTHONPATH environment
  variable.  (It must then also be on PYTHONPATH whenever you run
  Python and want to use the package(s) you are installing.)

* You can set up the installation directory to support ".pth" files by
  using one of the approaches described here:

  https://setuptools.readthedocs.io/en/latest/easy_install.html#custom-installation-locations

Please make the appropriate changes for your system and try again.